### PR TITLE
Release: 0.7.1

### PR DESCRIPTION
**Pull request by jamesjwarren**
## Changes in 0.7.1

 * @jamesjwarren: Feature: update linting (#31)
 * @jamesjwarren: Fix: script quote mark (#30)
 * @jamesjwarren: Feature: base docker config (#29)

### CODE REVIEW

**Comment by edwardoparearyee** [comment]
:+1: good to go once green

**Comment by jamesjwarren** [comment]
@edwardoparearyee safari8.1 e2e is failing the e2e, any ideas?

**Comment by edwardoparearyee** [comment]
Looks like saucelabs have dropped an OS/browser combo :disappointed: 

```
[safari 8.1 OS X 10.11 #3] UnknownCommandError: Unsupported OS/browser/version/device combo: OS: 'Mac 10.11', Browser: 'safari', Version: '8.1.', Device: 'unspecified'
```

Really naughty of them to drop it once introduced. You'll have to choose another version of safari from [here](https://docs.saucelabs.com/reference/platforms-configurator/#/)

**Comment by jamesjwarren** [comment]
@edwardoparearyee ahh thanks, missed that! Updated the version.

**Pull request merged**
